import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";
import { Providers } from "@/providers";
import "./globals.css";
import { ThemeTamplate } from "@/components/ui/templates/ThemeTamplate";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <ThemeTamplate>
        <html lang="en" suppressHydrationWarning={true}>
          <body className={twMerge(inter.className, "antialiased")}>
            {children}
          </body>
        </html>
      </ThemeTamplate>
    </Providers>
  );
}
